### PR TITLE
Update exercises.ml

### PR DESCRIPTION
**Pull request by morelvictor**
Hi, there is a compiling error without my patch

### CODE REVIEW

**Comment by morelvictor** [comment]
There is a compiling error without my patch

**Comment by johnwhitington** [comment]
Thanks!

**Comment by johnwhitington** [comment]
I merged this without testing.

But now, I just tested this on OCaml 4.13.0 and OCaml 5.00.0+trunk and get no errors with the old code.

What error do you see? And what OCaml version are you using?

**Comment by morelvictor** [comment]
I use OCaml 4.13.1
And I get the following error with the old code:
```
File "bin/ex3.ml", lines 53-57, characters 6-28:
53 | ......{Gc.minor_words;
54 |        Gc.promoted_words;
55 |        Gc.major_words;
56 |        Gc.minor_collections;
57 |        Gc.major_collections}
Error (warning 9 [missing-record-field-pattern]): the following labels are not bound in this record pattern:
heap_words, heap_chunks, live_words, live_blocks, free_words, free_blocks, largest_free, fragments, compactions, top_heap_words, stack_size, forced_major_collections
Either bind these labels explicitly or add '; _' to the pattern.
```

**Comment by johnwhitington** [comment]
Thanks.

This warning 9 is not on by default in OCaml: it's on by default with Dune. Are you using Dune to build?

**Comment by morelvictor** [comment]
Oh yes i'm using dune, i'm sorry if it was not an error

**Comment by johnwhitington** [comment]
Ok, so there are two things going on here:

a) You (or Dune) have Warning 9 on, which isn't on by default; and
b) You (or Dune) have warnings-as-errors on, which turns the warning into an error, which also isn't the default.

So, I'll revert this PR for now. But thanks for raising it anyway.

**Pull request merged**
